---
- name: FIREWALLD | Install the latest version of Firewalld
  yum:
    name: firewalld
    state: latest

- name: FIREWALLD | Start service firewalld, if not started
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
