---
- name: APACHE | Install the latest version of Firewalld
  yum:
    name: firewalld
    state: latest
- name: APACHE | Start service firewalld, if not started
  service:
    name: firewalld
    state: started
    enabled: yes
