---
- name: FTP | Install the latest version of vsftpd
  ansible.builtin.yum:
    name: vsftpd
    state: latest

- name: FTP | Start service vsftpd, if not started
  ansible.builtin.service:
    name: vsftpd
    state: started
    enabled: yes

- name: FTP | Put config from template 
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify:
    - FTP | Restart vsftpd