---
- name: APACHE | Install the latest version of Apache
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: APACHE | Enable service httpd
  ansible.builtin.systemd:
    name: httpd
    state: stopped
    enabled: yes

- name: APACHE | Creating a file with content
  ansible.builtin.copy:
    dest: "/var/www/html/index.html"
    content: |
      Welcome to my web server
      The current 
      date: {{ ansible_date_time.date }}

- name: APACHE | Enable HTTP porn on firewall {{ http_port }}/tcp
  ansible.builtin.firewalld:
    port: "{{ http_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - FIREWALLD | Reload Firewalld

- name: APACHE | Put config from template
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf

- name: APACHE | Start service httpd, if not started
  ansible.builtin.systemd:
    name: httpd
    state: started
