---
- hosts: web
  gather_facts: yes
  become: yes
  tasks:
    - name: FIREWALLD | Install
      include_role:
        name: install_firewalld

    - name: APACHE | Install
      vars:
        http_port: 8080
      include_role:
        name: install_apache

    - name: FTP | Install
      vars:
        ftpd_banner: "Welcome to My FTP service."
        ftp_folders:
          - upload
      include_role:
        name: install_ftp
